# Generated by Django 3.0.8 on 2020-07-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0002_auto_20200707_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogSite.BlogPost'),
        ),
    ]
