# Generated by Django 3.0.8 on 2020-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0003_comment_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Accomplished', 'Accomplished')], max_length=100, null=True)),
                ('github_link', models.URLField(max_length=10000, null=True)),
            ],
        ),
    ]
