# Generated by Django 3.0.8 on 2020-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0004_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
